# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-distributed/all/minitest-distributed.rbi
#
# minitest-distributed-0.2.8

module Minitest
  def self.plugin_junitxml_init(options); end
  def self.plugin_junitxml_options(opts, options); end
end
