# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push

jobs:
  test_32:
    runs-on: ubuntu-latest
    container: ruby:3.2

    services:
      redis:
        image: redis
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy:2.5.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: gem install bundler && bundle install
    - name: Run tests
      run: bin/rake test
      env:
        REDIS_URL: redis://toxiproxy:22220
        TOXIPROXY_HOST: http://toxiproxy:8474

  test_31:
    runs-on: ubuntu-latest
    container: ruby:3.1

    services:
      redis:
        image: redis
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy:2.5.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: gem install bundler && bundle install
    - name: Run tests
      run: bin/rake test
      env:
        REDIS_URL: redis://toxiproxy:22220
        TOXIPROXY_HOST: http://toxiproxy:8474

  test_30:
    runs-on: ubuntu-latest
    container: ruby:3.0

    services:
      redis:
        image: redis
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy:2.5.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: gem install bundler && bundle install
    - name: Run tests
      run: bin/rake test
      env:
        REDIS_URL: redis://toxiproxy:22220
        TOXIPROXY_HOST: http://toxiproxy:8474

  test_27:
    runs-on: ubuntu-latest
    container: ruby:2.7

    services:
      redis:
        image: redis
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy:2.5.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: gem install bundler && bundle install
    - name: Run tests
      run: bin/rake test
      env:
        REDIS_URL: redis://toxiproxy:22220
        TOXIPROXY_HOST: http://toxiproxy:8474

  typecheck:
    runs-on: ubuntu-latest
    container: ruby:2.7
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: gem install bundler && bundle install
    - name: Typecheck Ruby code
      run: bin/srb tc

  lint:
    runs-on: ubuntu-latest
    container: ruby:3.2
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: gem install bundler && bundle install
    - name: Lint Ruby code
      run: bin/rubocop
